name: Create New RSPEC

# Workflow runs when manually triggered using the UI or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      languages:
        description: 'Comma-separated list of targeted languages'
        required: true

jobs:
  create_new_rule:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        #repository: 'nicolas-harraudeau-sonarsource/test-github-actions'
        #token: ${{ secrets.NHARRAUD_PUBLIC_REPOS }}
        persist-credentials: true
        ref: rspec-id-counter
        path: 'rspec-id-counter'
    - uses: actions/checkout@v2
      with:
        persist-credentials: true
        ref: master
        path: 'master'
    - name: 'Configure Git'
      working-directory: 'rspec-id-counter'
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "<${{ github.actor }}@users.noreply.github.com>"

    - name: 'Increment the RSPEC ID counter'
      id: increment-rspec-id
      working-directory: 'rspec-id-counter'
      run: ../master/scripts/reserve_rspec_id.sh next_rspec_id.txt

    - name: 'Test RSPEC ID'
      run: echo $RSPEC_ID
    - name: 'print actor'
      run: echo $GITHUB_ACTOR

    - name: 'Create new rule in a branch'
      working-directory: 'master'
      run: ./scripts/create_new_rspec_branch.sh $RSPEC_ID "${{ github.event.inputs.languages }}" rules

    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v3
      with:
        path: 'master'
        commit-message: Create rule ${{ steps.increment-rspec-id.outputs.rspec-id }}
        title: Create rule ${{ steps.increment-rspec-id.outputs.rspec-id }}
        committer: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        assignees: "${{ github.actor }}"
        branch: add-RSPEC-${{ steps.increment-rspec-id.outputs.rspec-id }}
        draft: true

    - name: Check outputs
      run: |
        echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
        echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"