name: Create New RSPEC

# Workflow runs when manually triggered using the UI or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      languages:
        description: 'Comma-separated list of targeted languages'
        required: true

jobs:
  create_new_rule:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
      with:
        persist-credentials: true
        ref: rspec-id-counter
        path: 'rspec-id-counter'
    - name: 'Increment the RSPEC ID counter'
      working-directory: 'rspec-id-counter'
      run: ./scripts/reserve_rspec_id.sh
    - name: 'Test RSPEC ID'
      run: echo $RSPEC_ID
