name: Create New RSPEC

# Workflow runs when manually triggered using the UI or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      languages:
        description: 'Comma-separated list of targeted languages'
        required: true

jobs:
  create_new_rule:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: true
        ref: rspec-id-counter
        path: 'rspec-id-counter'
    - uses: actions/checkout@v2
      with:
        persist-credentials: true
        ref: master
        path: 'master'
    - name: 'Configure Git'
      working-directory: 'rspec-id-counter'
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
    - name: 'Increment the RSPEC ID counter'
      working-directory: 'rspec-id-counter'
      run: ../master/scripts/reserve_rspec_id.sh next_rspec_id.txt
    - name: 'Test RSPEC ID'
      run: echo $RSPEC_ID
